import {
  Eraser,
  Paintbrush,
  Bean,
  ShieldPlus,
  Backpack,
  IceCreamBowl,
  Wheat,
  Fish,
  Baby,
  Package,
  SprayCan,
  Drumstick,
  GlassWater,
  Phone,
  Pizza,
  Apple,
  Droplet,
  BatteryCharging,
  Pill,
  Shirt,
  Circle,
  Car,
  HeartPulse,
  Snowflake,
  Bug,
  Cake,
  Box,
  Trash,
  Utensils,
  Wind,
  Clock,
  Refrigerator,
  Croissant,
  Beer,
  Home,
  Egg,
  Flag,
  Coffee,
  WashingMachine,
  Milk,
  HelpCircle,
  Wine,
  Sun,
  Dog,
  Sunrise,
  Book,
  Eye,
  TreePine,
  Cookie,
  Calendar,
  Bone,
  Venus,
  CreditCard,
  Flower,
  Key,
  User,
  Donut,
  Candy,
  Smartphone,
  Salad,
  Sandwich,
  Drill,
  ScrollText,
} from "lucide-react";

const categorias = [
  { name: undefined, icon: ScrollText },
  { name: "TORTILLERIA MASA", icon: Wheat },
  { name: "ROSTIZADOS", icon: Drumstick },
  { name: "SHAMPOO", icon: Eraser },
  { name: "ACCESORIOS BEBES", icon: Baby },
  { name: "ALUMINIO", icon: Package },
  { name: "ALIMENTOS BEBE", icon: Baby },
  { name: "MARISCOS", icon: Fish },
  { name: "CREMAS Y TRATAMIENTOS", icon: SprayCan },
  { name: "ATUN", icon: Fish },
  { name: "DETERGENTES", icon: Eraser },
  { name: "SERVILLETAS", icon: Package },
  { name: "CARNE DE PUERCO", icon: Drumstick },
  { name: "QUESOS GRANEL", icon: Milk },
  { name: "REFRESCOS", icon: GlassWater },
  { name: "HIELO", icon: IceCreamBowl },
  { name: "PURES DE TOMATE", icon: Apple },
  { name: "TOSTADAS", icon: Circle },
  { name: "MUFFIN", icon: Cake },
  { name: "TELEFONIA", icon: Phone },
  { name: "CEREALES", icon: Wheat },
  { name: "COMIDA RAPIDA", icon: Pizza },
  { name: "LIMPIADORES", icon: SprayCan },
  { name: "FRUTAS Y VERDURAS", icon: Apple },
  { name: "BEBIDA GATORADE Y SUEROS", icon: Droplet },
  { name: "BEBIDAS ENERGETICAS", icon: BatteryCharging },
  { name: "CUIDADO BUCAL", icon: ShieldPlus },
  { name: "FARMACIA", icon: Pill },
  { name: "ROPA", icon: Shirt },
  { name: "GOMA DE MASCAR", icon: Circle },
  { name: "CHILES ENVASADOS", icon: Package },
  { name: "LAVATRASTES", icon: Eraser },
  { name: "VARIEDADES", icon: Package },
  { name: "AUTOS", icon: Car },
  { name: "CARNICERIA RES", icon: Drumstick },
  { name: "GINECOLOGICOS OTC Y PROD SEX", icon: HeartPulse },
  { name: "VEGETALES Y FRUTAS CONGELADOS", icon: Snowflake },
  { name: "INSECTICIDAS", icon: Bug },
  { name: "PASTEL", icon: Cake },
  { name: "PRODUCTO DE CARNICERIA", icon: Drumstick },
  { name: "ACCESORIOS REPOSTERIA", icon: Cake },
  { name: "COMBOS", icon: Box },
  { name: "CONSOMES", icon: Utensils },
  { name: "OTC", icon: HelpCircle },
  { name: "BOTANAS", icon: Package },
  { name: "CONCENTRADOS EN POLVO", icon: Package },
  { name: "FEITE", icon: Droplet },
  { name: "ANALGESICOS", icon: Pill },
  { name: "HARINA 1MPLE", icon: Wheat },
  { name: "DESECHABLES", icon: Trash },
  { name: "MATERIAL ELECTRICO/CERRAJERIA", icon: Key },
  { name: "COMIDAS", icon: Utensils },
  { name: "TORTILLAS", icon: Circle },
  { name: "SUAVIZANTES", icon: Wind },
  { name: "MERMELADAS, MIELES Y CAJETAS", icon: Package },
  { name: "PERECEDEROS", icon: Clock },
  { name: "REFRIGERADOS", icon: Refrigerator },
  { name: "ADEREZOS", icon: Package },
  { name: "COMPLEMENTOS PASTEL", icon: Cake },
  { name: "CARNICERIA POLLO", icon: Drumstick },
  { name: "BOLLERIA", icon: Croissant },
  { name: "BEBIDAS Y SNACKS", icon: Beer },
  { name: "COSTAL", icon: Package },
  { name: "Varios", icon: Package },
  { name: "HOGAR Y PAPEL", icon: Home },
  { name: "GRANOS BOLSA", icon: Wheat },
  { name: "CAJAS", icon: Box },
  { name: "CARNE DE POLLO Y AVES", icon: Drumstick },
  { name: "BACKPACKUETTE", icon: Sandwich },
  { name: "HUEVO", icon: Egg },
  { name: "PAN EMPACADO", icon: Sandwich },
  { name: "COMIDA MEXICANA", icon: Flag },
  { name: "HARINA SIMPLE", icon: Wheat },
  { name: "REPOSTERIA", icon: Cake },
  { name: "DANES", icon: Flag },
  { name: "BEBIDAS Y SNACK", icon: Beer },
  { name: "CAFE FRASCO", icon: Coffee },
  { name: "HIGIENE Y CUIDADO PERSONAL", icon: Eraser },
  { name: "SAL, MOLES Y SALSA SOYA", icon: Package },
  { name: "LAVANDERIA", icon: WashingMachine },
  { name: "PIZZA", icon: Pizza },
  { name: "YOGURTH", icon: Milk },
  { name: "MAYOREO", icon: Box },
  { name: "NULL", icon: HelpCircle },
  { name: "HARINA PASTEL", icon: Wheat },
  { name: "DESODORANTES", icon: SprayCan },
  { name: "EMBALAJE PANADERIA", icon: Package },
  { name: "BOCADILLOS", icon: Utensils },
  { name: "CAFES GRA0", icon: Coffee },
  { name: "ARROZ BOLSA", icon: Wheat },
  { name: "LECHES FRESCAS", icon: Milk },
  { name: "VINOS Y LICORES", icon: Wine },
  { name: "GRANOLAS, BARRAS Y AVENAS", icon: Bean },
  { name: "PURINAS Y GRANOS", icon: Wheat },
  { name: "TRACTO ALIMENTARIO Y METABOL", icon: Pill },
  { name: "CARBON", icon: Package },
  { name: "AZUCAR", icon: Package },
  { name: "BEBIDA INFANTIL", icon: Baby },
  { name: "PAÑALES", icon: Baby },
  { name: "ESPECIES Y CONDIMENTOS", icon: Package },
  { name: "ACCESORIOS PARA MASCOTAS", icon: Dog },
  { name: "BEBIDA GALON", icon: Droplet },
  { name: "DESAYUNOS", icon: Sunrise },
  { name: "FRUTAS ENVASADAS", icon: Apple },
  { name: "POSTRES", icon: Cake },
  { name: "SABORIZANTES LECHE", icon: Milk },
  { name: "PAPELERIA", icon: Book },
  { name: "CASA", icon: Home },
  { name: "FIBRAS, LAZO Y MERCERIA.", icon: Package },
  { name: "LACTEOS Y SALCHICHONERIA", icon: Milk },
  { name: "MERCANCIAS GENERALES", icon: Package },
  { name: "OFTALMOLOGICOS Y OTICOS OTC", icon: Eye },
  { name: "SALSAS ENVASADAS", icon: Package },
  { name: "DERMATOLOGICOS", icon: Pill },
  { name: "FERRETERIA", icon: Drill },
  { name: "SUEROS ORALES", icon: Droplet },
  { name: "TORTILLERIA", icon: Circle },
  { name: "ARTICULOS NAVIDEÑOS", icon: TreePine },
  { name: "CLOROS Y QUITAMANCHAS", icon: Package },
  { name: "GALLETAS", icon: Cookie },
  { name: "SARTENES Y UTENSILIOS", icon: Utensils },
  { name: "BOLSAS", icon: Backpack },
  { name: "DELICATESSEN PAQUETERIA", icon: Package },
  { name: "PERFUMERIA", icon: SprayCan },
  { name: "TEMPORADA", icon: Calendar },
  { name: "PAN BLANCO", icon: Sandwich },
  { name: "TES", icon: Coffee },
  { name: "SECOS", icon: Sun },
  { name: "CARNE DE RES", icon: Drumstick },
  { name: "AGUA NATURAL", icon: Droplet },
  { name: "ALIMENTOS GRANEL", icon: Wheat },
  { name: "FRIJOL BOLSA", icon: Wheat },
  { name: "MASCOTAS Y ANIMALES", icon: Dog },
  { name: "COMIDAS MASCOTAS", icon: Bone },
  { name: "LECHES UHT", icon: Milk },
  { name: "CARNICOS", icon: Drumstick },
  { name: "CUIDADO FEMENINO", icon: Venus },
  { name: "GRANELES", icon: Wheat },
  { name: "ESCOBAS Y TRAPEADORES", icon: Paintbrush },
  { name: "LECHES SABORIZADAS", icon: Milk },
  { name: "POS", icon: CreditCard },
  { name: "CONGELADOS", icon: Snowflake },
  { name: "SALSAS Y COMPLEMENTOS", icon: Package },
  { name: "HARINA HOT CAKES", icon: Wheat },
  { name: "AROMATIZANTES", icon: Flower },
  { name: "CERRAJERIA", icon: Key },
  { name: "CERAS Y VELADORAS", icon: Package },
  { name: "COMIDAS PREPARADAS", icon: Utensils },
  { name: "DESAYU0S", icon: Sunrise },
  { name: "FLORERIA", icon: Flower },
  { name: "CERVEZAS", icon: Beer },
  { name: "CUIDADO PERSONAL", icon: User },
  { name: "JUGOS Y NECTARES", icon: GlassWater },
  { name: "QUESOS PAQUETERIA", icon: Milk },
  { name: "COSMETICOS", icon: SprayCan },
  { name: "GELATINAS Y POSTRES", icon: Cake },
  { name: "DONA", icon: Donut },
  { name: "CREMAS", icon: Package },
  { name: "MATERIA PRIMA", icon: Box },
  { name: "BIZCOCHO", icon: Cake },
  { name: "FORMULAS BEBE", icon: Baby },
  { name: "ROPA INTERIOR", icon: Shirt },
  { name: "TELEFONIA TELCEL", icon: Phone },
  { name: "GASTROINTESTINALES", icon: Pill },
  { name: "CAFES", icon: Coffee },
  { name: "CAFES GRANO", icon: Coffee },
  { name: "MEDICINA ETICA", icon: Pill },
  { name: "DULCERIA", icon: Candy },
  { name: "SOPAS INSTANTANEAS", icon: Utensils },
  { name: "TELAS Y RECOJEDORES", icon: Package },
  { name: "ELECTRONICA Y ACCESORIOS", icon: Smartphone },
  { name: "ACEITES", icon: Droplet },
  { name: "HOGAR", icon: Home },
  { name: "CIGARROS", icon: Package },
  { name: "CREMAS PARA CAFE", icon: Coffee },
  { name: "PASTAS", icon: Wheat },
  { name: "GRA0LAS, BARRAS Y AVENAS", icon: Bean },
  { name: "CAFETERIA", icon: Coffee },
  { name: "VERDURAS ENLATADAS", icon: Package },
  { name: "SNACK Y BOTANAS", icon: Package },
  { name: "AUTOMOTRIZ", icon: Car },
  { name: "SALCHICHONERIA PAQUETE", icon: Package },
  { name: "GALLETERIA", icon: Cookie },
  { name: "ENSALADAS", icon: Salad },
  { name: "CARNICERIA PUERCO", icon: Drumstick },
  { name: "PAN DE TEMPORADA", icon: Sandwich },
  { name: "TOTOPOS Y TOSTADAS", icon: Circle },
  { name: "AGUA SABORIZADA Y TES", icon: Coffee },
  { name: "BEBIDAS PREPARADAS", icon: GlassWater },
  { name: "HIGIENICOS", icon: Eraser },
  { name: "ABARROTES", icon: Box },
  { name: "HERRAMIENTA", icon: Drill },
  { name: "PAN EUROPEO", icon: Sandwich },
];

export default categorias;
