import { Field } from "../interfaces";

export function TestInputsField(): Field[] {
  return [
    {
      type: "Flex",
      name: "flex",
      label: "Flex",
      require: false,
      elements: [
        {
          id: 0,
          type: "INPUT",
          name: "nombre",
          label: "example flex 1",
          placeholder: "Nombre",
          require: false,
        },
        {
          id: 1,
          type: "PHONE",
          name: "telefono",
          label: "example flex 2",
          placeholder: "Teléfono",
          require: true,
        },
      ],
    },
    {
      id: 0,
      type: "INPUT",
      name: "usuarios",
      label: "Nombre de usuario",
      placeholder: "Nombre",
      require: true,
    },
    {
      id: 1,
      type: "PHONE",
      name: "t1",
      label: "Teléfono",
      placeholder: "Descripción",
      require: false,
    },
    {
      id: 1,
      type: "TEXT_AREA",
      name: "t2",
      label: "Experiencia",
      placeholder: "Descripción",
      require: false,
      maxLength: 100,
    },
    {
      id: 1,
      type: "MAIL",
      name: "t3",
      label: "Correo",
      placeholder: "Descripción",
      require: false,
    },
    {
      id: 2,
      type: "DATE",
      name: "fechaInicio",
      label: "Fecha de nacimiento",
      placeholder: "Fecha Inicio",
      require: false,
    },
    {
      id: 3,
      type: "DATE_RANGE",
      name: "fechaFin",
      label: "Fechas de entrevista",
      placeholder: "Fecha Fin",
      require: false,
    },
    {
      id: 4,
      type: "CHECKBOX",
      name: "activo",
      label: "Acepto los términos y condiciones",
      placeholder: "Estado",
      require: false,
    },
    {
      id: 4,
      type: "CHECKBOX_GROUP",
      options: ["Activo", "Pendiente", "Inactivo", "Finalizado"],
      name: "t4",
      label: "Fortalezas",
      placeholder: "Estado",
      require: false,
    },
    {
      id: 5,
      type: "SELECT",
      options: [
        "JavaScript",
        "React",
        "Node.js",
        "Python",
        "Java",
        "C++",
        "Ruby",
        "PHP",
        "HTML",
        "CSS",
        "TypeScript",
        "Angular",
        "Vue.js",
        "Django",
        "Flask",
        "Express.js",
        "MongoDB",
        "SQL",
        "Git",
        "Docker",
        "AWS",
        "Azure",
        "GraphQL",
        "REST API",
        "Machine Learning",
        "Data Analysis",
        "Agile",
        "Scrum",
      ],
      enableAutocomplete: "true",
      name: "state",
      label: "Habilidades",
      placeholder: "Prioridad",
      require: false,
      multi: false,
    },
    {
      id: 5,
      type: "FILE",
      name: "nombre",
      label: "archivo",
      placeholder: "Nombre",
      require: false,
    },
    {
      id: 5,
      type: "IMG",
      name: "t5",
      label: "Foto de perfil",
      placeholder: "Nombre",
      require: false,
    },
  ];
}
