export const styles = {
  formContainer: { marginBottom: "20px" },
  fileLabel: { display: "block", marginBottom: "10px" },
  submitButton: {
    padding: "10px 20px",
    backgroundColor: "#0070f3",
    color: "white",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
  },
  message: { marginTop: "20px", color: "#0070f3" },
  tableContainer: { width: "90%", margin: "auto" },
  table: {
    marginTop: "20px",
    borderCollapse: "collapse",
    boxShadow: "0 0 10px rgba(0, 0, 0, 0.1)",
    borderRadius: "8px",
    overflowX: "auto",
  },
  tableHeader: {
    backgroundColor: "#0070f3",
    color: "white",
    textAlign: "left" as const,
    padding: "12px 15px",
    fontWeight: "600",
    textTransform: "uppercase" as const,
  },
  tableCell: {
    padding: "12px 15px",
    color: "#333333",
    fontSize: "14px",
  },
  downloadLink: {
    padding: "6px 12px",
    backgroundColor: "#0070f3",
    color: "white",
    borderRadius: "5px",
    textDecoration: "none",
    fontSize: "14px",
    transition: "background-color 0.3s ease",
    display: "inline-block",
  },
  paginationContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "1rem",
    marginTop: "20px",
  },
  paginationButton: {
    padding: "8px 16px",
    backgroundColor: "#0070f3",
    color: "white",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    disabled: {
      opacity: 0.5,
      cursor: "not-allowed",
    },
  },
  pageInfo: {
    color: "#333",
    fontSize: "14px",
  },
};
